### ISSUE TITLE
Hover style is not applied correctly to Pressable components

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#12]
### Description

Hover style is not applied correctly to Pressable components. For some reason, Pressable components are not passing `borderRadius` to the native side correctly. 

![CleanShot 2023-10-20 at 12 19 12@2x](https://github.com/callstack/react-native-visionos/assets/52801365/f3c4c024-74cb-44fb-9868-9df7a7892329)

**Comment by Aakashdeep-Srivastava** [comment]
let's do this.... Assign me

**Comment by Marcoo09** [comment]
Hi @okwasniewski, I was not able to reproduce it. It was solved?

**Comment by okwasniewski** [comment]
Hey @Marcoo09,

No it wasn't fixed. If you go to Components > Pressable and modify `ContentPress` function like so:

```diff
function ContentPress() {
  const [timesPressed, setTimesPressed] = useState(0);

  let textLog = '';
  if (timesPressed > 1) {
    textLog = timesPressed + 'x onPress';
  } else if (timesPressed > 0) {
    textLog = 'onPress';
  }

  return (
    <>
      <View style={styles.row}>
        <Pressable
+          style={{padding: 10, borderRadius: 20, backgroundColor: 'red'}}
          onPress={() => {
            setTimesPressed(current => current + 1);
          }}>
          {({pressed}) => (
            <Text testID="one_press_me_button" style={styles.text}>
              {pressed ? 'Pressed!' : 'Press Me'}
            </Text>
          )}
        </Pressable>
      </View>
      <View style={styles.logBox}>
        <Text testID="pressable_press_console">{textLog}</Text>
      </View>
    </>
  );
}
```

You will see that borderRadius is not correctly applied for hoverStyle

![CleanShot 2023-12-12 at 10 22 41@2x](https://github.com/callstack/react-native-visionos/assets/52801365/7b9f7214-5128-4802-8a83-8c5bd9e04c6f)

**Comment by gokul1099** [comment]
I gone through this issue, In RCTViewComponentView.cpp, self.layers.cornerRadius becomes 0.0. because of that *shape is created with 0 borderRadius.

<img width="731" alt="image" src="https://github.com/callstack/react-native-visionos/assets/42144106/7329b84a-8d3f-47e2-b85c-fb2e931ff686">

 If we pass any custom value like 
` UIShape *shape = [UIShape rectShapeWithCornerRadius: CGFloat(20)];` it is working fine

**Comment by okwasniewski** [comment]
@gokul1099 Maybe we need to use `RCTCornerRadiiFromBorderRadii` / track where `layer.cornerRadius` is set back to 0. I think this is a bug somewhere deep in RN

**Comment by gokul1099** [comment]
> I gone through this issue, In RCTViewComponentView.cpp, self.layers.cornerRadius becomes 0.0. because of that *shape is created with 0 borderRadius.
> 
> <img alt="image" width="731" src="https://private-user-images.githubusercontent.com/42144106/290466075-7329b84a-8d3f-47e2-b85c-fb2e931ff686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MTY1MDgsIm5iZiI6MTcwMjYxNjIwOCwicGF0aCI6Ii80MjE0NDEwNi8yOTA0NjYwNzUtNzMyOWI4NGEtOGQzZi00N2UyLWI4NWMtZmIyZTkzMWZmNjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA0NTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzczNzNjMmY2MDQ5MGJkZGI1N2VlZDA4ZTBiM2Q5N2M0ZTlmYTE3NGE4NzA0YTM5NGQyOWFjYjc3YTc5NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aDtUzjM92il7eDm2F9xTSk9VRqbJhz9MIWuCkKOr_HY">
> If we pass any custom value like ` UIShape *shape = [UIShape rectShapeWithCornerRadius: CGFloat(20)];` it is working fine @okwasniewski Do you have any idea on this ?

I have found something. whenever we update the borderRadius the updateHoverEffect is not getting triggered. So I made some changes like below so it will get triggered everytime props changes. After this change the borderRadius working fine.
(only if we change the props borderRadius value)
![image](https://github.com/callstack/react-native-visionos/assets/42144106/f3ff564b-c4dd-45e8-a67a-c672cdfcc736)
screenshot after above changes ->
![image](https://github.com/callstack/react-native-visionos/assets/42144106/18ea18ff-eb75-4a69-a0e0-3113dafee5f2)

But in the initial render the self.layers.cornerRadius in updateHoverEffect is 0.0. So the borderRadius is not getting applied.
@okwasniewski  Can we send the borderRadius as parameter to updateHoverEffect like the hoverEffect string we are passing `updateHoverEffect:[NSString stringWithUTF8String:newViewProps.visionos_hoverEffect.c_str()]` ??
